#!/usr/bin/python3

# System modules
import tkinter as tk
import serial
import time
import obd
from tkinter import ttk
from queue import Queue
from threading import Thread

# Set up some global variables
num_fetch_threads = 1
queue = Queue()

# This gets the data from the ELM237 BT module
def readFromELM(command):
  fromELM = connection.query(command)
  #todo: figure out how to differ commands and convert speed to mph
  printf(command)
  magnitude = str(fromELM.value.magnitude)
  return magnitude;

# This is the thread that reads from the Ardino
def readData(app, q):
  print("*** Read thread running")
  connection = obd.OBD()
  speed = obd.commands.SPEED
  rpm = obd.commands.RPM
  eng_temp = obd.commands.COOLANT_TEMP
  fuel_level = obd.commands.FUEL_LEVEL
  intake_temp = obd.commands.INTAKE_TEMP
  while True:
    if(connection.query(speed)):
      data = [
        readFromELM(speed),       #data[0]
        readFromELM(rpm),         #data[1]
        readFromELM(eng_temp),    #data[2]
        readFromELM(fuel_level),  #etc.
        readFromELM(intake_temp)
      ]
      q.put(data)
      q.task_done()

# Update Gauge Values
def updateGauges(app, q):
  print("*** Update thread running")
  while True:
    time.sleep(.05)
    data = q.get()

    app.MPH["value"] = float(data[0])
    app.labelMPH["value"] = data[0] + " MPH"

    app.RPM["value"] = float(data[1])
    app.labelTemp["value"] = data[1] + "RPM"

    app.Temp["value"] = float(data[2])
    app.labelTemp["value"] = "Engine Temp " + data[2] + "C"

    app.fuelLevel["value"] = float(data[3])
    app.labelFuelLevel["value"] = "Fuel Level " + data[3] + "%"

    app.intakeTemp["value"] = float(data[4])
    app.labelIntakeTemp["value"] = "Intake Temp " + data[4] + "C"

# Declare a class for the GUI
class Dash(tk.Tk):

  def __init__(self):
    # Init
    tk.Tk.__init__(self)
    style = ttk.Style()
    style.configure("BW.TLabel", foreground="black")
    self.geometry('800x480')

    # Set up the different screens
    notebook = ttk.Notebook(self)
    screen1 = ttk.Frame(notebook)
    screen2 = ttk.Frame(notebook)
    notebook.add(screen1, text='Screen 1')
    notebook.add(screen2, text='Screen 2')
    notebook.pack()

    # TEMP
    labelTemp = ttk.Label(screen1, text="Engine Temp C", style="BW.TLabel")
    labelTemp.pack()
    Temp = ttk.Progressbar(screen1, orient="horizontal", length=800,
                               mode="determinate", value=0, maximum=250)
    Temp.pack()

    # RPM
    labelRPM = ttk.Label(screen1, text="RPM", style="BW.TLabel")
    labelRPM.pack()
    RPM = ttk.Progressbar(screen1, orient="horizontal", length=800,
                               mode="determinate", value=0, maximum=7000)
    RPM.pack()

    # MPH
    labelMPH = ttk.Label(screen2, text="MPH", style="BW.TLabel")
    labelMPH.pack()
    MPH = ttk.Progressbar(screen2, orient="horizontal", length=800,
                               mode="determinate", value=0, maximum=120)
    MPH.pack()

    # Fuel Level
    labelFuelLevel = ttk.Label(screen2, text="Fuel Level", style="BW.TLabel")
    labelFuelLevel.pack()
    fuelLevel = ttk.Progressbar(screen2, orient="horizontal", length=800,
                               mode="determinate", value=0, maximum=100)
    fuelLevel.pack()

    # Intake Temp
    labelIntakeTemp = ttk.Label(screen2, text="Intake Temp", style="BW.TLabel")
    labelIntakeTemp.pack()
    intakeTemp = ttk.Progressbar(screen2, orient="horizontal", length=800,
                               mode="determinate", value=0, maximum=200)
    intakeTemp.pack()


print('*** Main thread running')

app = Dash()

# Set up some threads
read = Thread(target=readData, args=(app, queue,))
read.setDaemon(True)
read.start()

update = Thread(target=updateGauges, args=(app, queue,))
update.setDaemon(True)
update.start()

app.mainloop()

queue.join()
print('*** Done')
