#!/usr/bin/python3

# Screen Size
WIDTH = 800
HIGHT = 480

# RPM
RPM_MAX = 9000
RPM_COLOR = 'white'
RPM_WARNING = 7000
RPM_WARNING_COLOR = 'yellow'
RPM_RED_LINE = 8500
RPM_RED_LINE_COLOR1 = 'white'
RPM_RED_LINE_COLOR2 = 'red'

# Fuel - this is a percent
FUEL_MAX = 100
FUEL_WARNING = 15
FUEL_WARNING_COLOR = 'yellow'
FUEL_CRITICAL = 5 
FUEL_CRITICAL_COLOR1 = 'blue'
FUEL_CRITICAL_COLOR2 = 'white'

# Engine Temp
ENGINE_TEMP_MAX = 350
ENGINE_TEMP_COLOR = 'white'
ENGINE_TEMP_WARNING = 250
ENGINE_TEMP_WARNING_COLOR = 'yellow'
ENGINE_TEMP_CRITICAL = 300
ENGINE_TEMP_CRITICAL_COLOR1 = 'red'
ENGINE_TEMP_CRITICAL_COLOR2 = 'yellow'

# Intake Temp
